### ISSUE TITLE
XSAMPA fixes

### ISSUE THREAD

**Issue by meficat** [alexbenenson/transliterator#2]
Hi.

First of all, the add-on is great. I have been using it for some time in order to type IPA symbols. There have been, however, some issues with the “Phonetics (XSAMPA)” mapping, so I'd like to share my list of fixes and tweaks.

### r` shadowing
There is a bug in the definition that causes the sequence to be shadowed by a previous one (`ɻ` is defined as ``r` ``, but it should be ``r\` ``):
```javascript
["r`","ɽ"],
["r\\","ɹ"],
["r`","ɻ"],
```
The third mapping needs to be changed to:
```javascript
["r\\`","ɻ"],
```

### wrong character for I\
The sequence `I\` points to `Ɨ` while it should to `ᵻ`. Change:
```javascript
["I\\","Ɨ"],
```
to
```javascript
["I\\","ᵻ"],
```

### wrong character for -\
The sequence `-\` points to `̮` while it should to `‿` (not a combining character). Change:
```javascript
["-\\","̮"],
```
to
```javascript
["-\\","‿"],
```

### custom tweaks
And here are some mappings that I have added to my custom table for quick access.

Upper (`^^`) and lower (`__`) tie bar (combining characters):
```javascript
["^^","͡"],
["__","͜"],
```

Non-modifying tilde (`~\`), useful for marking allophonic variation:
```javascript
["~\\","~"],
```

**Comment by palant** [comment]
Thank you, I fixed the issues you indicated. As to the custom tweaks, I don't think that these belong in the "official" layout. We should definitely make it easier to create custom layouts from the existing ones however.
